# -*- coding: utf-8 -*-
"""Agentic System to enhance RAG with Self-Grading and Web Search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfXj-ab8X1Ff7IA3C-9GV8b6cTkbSzuX
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install pydantic-ai
# %pip -q install nest_asyncio
# %pip -q install devtools
# %pip install 'pydantic-ai-slim[openai,groq,logfire]'
# %pip install tavily-python
# %pip install -qU langchain
# %pip install -qU langchain_community
# %pip install -qU sentence_transformers
# %pip install -qU langchain_huggingface
# %pip install pypdf

from google.colab import userdata
import os
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIModel
from pydantic_ai.models.groq import GroqModel

openai_model = OpenAIModel('gpt-4o-mini')
groq_model = GroqModel("llama-3.3-70b-versatile")

!pip install chromadb

from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
#
loader = PyPDFLoader("Fibro-Fact-Sheet.pdf")
documents = loader.load()
#
split_docs = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50).split_documents(documents)
#
#embeddings
embedding = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
#
#Build Index
vectorstore = Chroma.from_documents(
    documents=split_docs,
    embedding=embedding,
    persist_directory=persist_directory,
    collection_name="fibromyalgia"
)

from dataclasses import dataclass
@dataclass
class Deps:
    question:str |None
    context:str |None

import nest_asyncio
nest_asyncio.apply()
#
groq_agent = Agent(groq_model,
                   deps_type=Deps,
                    retries=2,
                    result_type=str,
                   system_prompt=("You are a Helpful Assiatnt Profiocient in Answering concise,factful and to the point asnwers for questions asked based on the Context provided"
                   "You have to Use the `retrievre_tool' to get relevent context and generate response based on the context retrieved"
                   """You are a grading assistant. Evaluate the response based on:
        1. Relevancy to the question
        2. Faithfulness to the context
        3. Context quality and completeness

        lease grade the following response based on:
        1. Relevancy (0-1): How well does it answer the question?
        2. Faithfulness (0-1): How well does it stick to the provided context?
        3. Context Quality (0-1): How complete and relevant is the provided context?

        Question: {ctx.deps.query}
        Context: {ctx.deps.context}
        Response: {ctx.deps.response}

        Also determine if web search is needed to augment the context.

        Provide the grades and explanation in the JSON format with key atrributes 'Relevancy','Faithfulness','Context Quality','Needs Web Search':
        {"Relevancy": <score>,
        "Faithfulness": <score>,
        "Context Quality": <score>,
        "Needs Web Search": <true/false>,
        "Explanation": <explanation>,
        "Answer":<provide response based on the context from the `retrievre_tool' if 'Need Web Search' value is 'false' otherwise Use the `websearch_tool` function to generate the final reaponse}"""
        ),
        )

@groq_agent.tool_plain
async def websearch_tool(question) -> str:
    """check if the square is a winner"""
    # Step 1. Instantiating your TavilyClient
    tavily_client = TavilyClient()

    # Step 2. Executing a Q&A search query
    answer = tavily_client.qna_search(query=question)

    # Step 3. That's it! Your question has been answered!
    print(f"WEB SEARCH:{answer}")
    return answer

from typing import List # Import List from typing

from pydantic_ai import Agent, RunContext # Import RunContext from pydantic_ai
from pydantic_ai.models.openai import OpenAIModel
from pydantic_ai.models.groq import GroqModel



@groq_agent.tool
async def rertiever_tool(ctx: RunContext[Deps], question: str) -> List[str]: # Use List in type hint


  load_vectorstore = Chroma(persist_directory=persist_directory, embedding_function=embedding,collection_name="fibromyalgia")
  docs = load_vectorstore.similarity_search(question,k=3)
  documnets = [d.page_content for d in docs]
  print(f"RAG Retrieval:{documnets}")
  return documnets

query = "What is Fibromyalgia?"
response = groq_agent.run_sync(query)
print(response)

response.data

response.cost()

query = "What is Fibromyalgia and what are it's causes?"
response = groq_agent.run_sync(query)
print(response)

from langchain_core.output_parsers import JsonOutputParser
print(response.data)
parser = JsonOutputParser()
print(parser.parse(response.data))
print(parser.parse(response.data)['Answer'])
print(response.cost())

query = "What is the life expectancy of people suffering with fibromyalgia?"
response = groq_agent.run_sync(query)
print(response.data)
parser = JsonOutputParser()
print(parser.parse(response.data))
print(parser.parse(response.data)['Answer'])
print(response.cost())

RAG Retrieval:['losing\tspondylitis\tare\talso\tmore\tlikely\t\nto\tdevelop\tfibromyalgia.\t\n• Symptoms usually appear between \nages 30 and 55. \n• Though more common in adults, chil -\ndren (especially adolescent girls) may \ndevelop\tfibromyalgia.\nFibromyalgia\nWE ARE CHAMPIONING THE FIGHT AGAINST ARTHRITIS   I  ARTHRITIS.ORG', 'Arthritis Fact Sheet Fibromyalgia\nMood and Concentration Problems – Feeling sad \nor being down is common. People with fibromyalgia \nalso may feel anxious and have difficulty concentrating \nor performing simple mental tasks. These problems tend \nto come and go and are often most prominent at times \nof extreme fatigue or anxiety. Some people with fibro-\nmyalgia have depression.\nOther Problems – Headaches, jaw pain, abdominal \nor pelvic pain, dizziness, restless legs and numbness or', 'conditions. The good news is that it’s not considered a \nprogressive disease. With proper treatment and lifestyle \nchanges, symptoms can improve.\nDoctors don’t know what causes fibromyalgia, but \nit most likely involves various factors and/or triggers \nworking together. These may include genes, infections \nor illnesses and physical or emotional trauma. \nSigns and Symptoms of Fibromyalgia \nFibromyalgia has been described as a constellation of']
RAG Retrieval:['losing\tspondylitis\tare\talso\tmore\tlikely\t\nto\tdevelop\tfibromyalgia.\t\n• Symptoms usually appear between \nages 30 and 55. \n• Though more common in adults, chil -\ndren (especially adolescent girls) may \ndevelop\tfibromyalgia.\nFibromyalgia\nWE ARE CHAMPIONING THE FIGHT AGAINST ARTHRITIS   I  ARTHRITIS.ORG', 'About Fibromyalgia\nFibromyalgia is a condition in which the main symptoms \nare widespread chronic pain and fatigue. The condition \nis considered a rheumatic disease like many forms of \narth ritis. But there are key differences. Fibromyalgia does \nnot cause inflammation or damage joints or muscles. \nFibromyalgia is not life-threatening but can affect \nmany aspects of daily life. It can occur by itself but may \nalso affect people with other forms of arthritis or chronic', 'Arthritis Fact Sheet Fibromyalgia\nMood and Concentration Problems – Feeling sad \nor being down is common. People with fibromyalgia \nalso may feel anxious and have difficulty concentrating \nor performing simple mental tasks. These problems tend \nto come and go and are often most prominent at times \nof extreme fatigue or anxiety. Some people with fibro-\nmyalgia have depression.\nOther Problems – Headaches, jaw pain, abdominal \nor pelvic pain, dizziness, restless legs and numbness or']
{"Relevancy": 0.6, "Faithfulness": 0.8, "Context Quality": 0.7, "Needs Web Search": true, "Explanation": "The provided context does not explicitly state the life expectancy of people suffering from fibromyalgia. However, it does mention that fibromyalgia is not life-threatening and can affect many aspects of daily life. It also provides information on the symptoms and effects of fibromyalgia, but does not provide a clear answer to the question about life expectancy.", "Answer": "The life expectancy of people suffering from fibromyalgia is not explicitly stated in the provided context. However, it is mentioned that fibromyalgia is not life-threatening. To get a more accurate answer, a web search is needed."}
{'Relevancy': 0.6, 'Faithfulness': 0.8, 'Context Quality': 0.7, 'Needs Web Search': True, 'Explanation': 'The provided context does not explicitly state the life expectancy of people suffering from fibromyalgia. However, it does mention that fibromyalgia is not life-threatening and can affect many aspects of daily life. It also provides information on the symptoms and effects of fibromyalgia, but does not provide a clear answer to the question about life expectancy.', 'Answer': 'The life expectancy of people suffering from fibromyalgia is not explicitly stated in the provided context. However, it is mentioned that fibromyalgia is not life-threatening. To get a more accurate answer, a web search is needed.'}
The life expectancy of people suffering from fibromyalgia is not explicitly stated in the provided context. However, it is mentioned that fibromyalgia is not life-threatening. To get a more accurate answer, a web search is needed.
Cost(request_tokens=2938, response_tokens=211, total_tokens=3149, details=None)